### ISSUE TITLE
word2vec: exception with just positive words and no negative

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-magpie#5]
If you use word2vec with just positive words and no negative, there is a server error.

Reported by @eamonnmag

**Comment by jstypka** [comment]
what's the error?

**Comment by jalavik** [comment]
The error is basically that in the check if the word exists in the corpus, empty string does not exist.

```
Traceback (most recent call last):
  File "/opt/magpie/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/magpie/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/magpie/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/magpie/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/magpie/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/magpie/lib/python2.7/site-packages/inspire_magpie/ui.py", line 69, in word2vec
    vector = get_word_vector('keywords', positive, negative)
  File "/opt/magpie/lib/python2.7/site-packages/inspire_magpie/api.py", line 92, in get_word_vector
    "in the {1} corpus".format(word, corpus))
WordDoesNotExist:  does not have a representation in the keywords corpus
```

**Comment by jstypka** [comment]
Ah, so I think the problem is on the frontend side. Because in the inspire-magpie REST API, you can provide a list for both `positive` and `negative` words and it's fine if there's only one of them. However in the HTML form - if somebody does not fill the box with negative words, we shouldn't send an empty string, but just skip the field altogether.
