### ISSUE TITLE
Getting ImportError: No module named evaluation.rank_metrics in Magpie2.0  Ubuntu 16 64 bit 

### ISSUE THREAD

**Issue by rajeshkumargp** [inspirehep/inspire-magpie#7]
I am trying to execute inspire-magpie with magpie-2.0 version, but it is failing since the current inspirehep-magpie code is  referring magpie-1.0/.  

Changes I have made: 

In api.py, renamed as 

```
from magpie import Magpie   #- (removed Magpiemodel)
from magpie.config import EPOCHS, BATCH_SIZE  # removed NB_EPOCHS 

``` 

While executing I am getting error due to the below line 

``` 
from magpie.evaluation.rank_metrics import mean_reciprocal_rank, r_precision, \
    mean_average_precision, ndcg_at_k, precision_at_k
``` 

Error message I am getting : 

```
$ python wsgi.py 
/home/user/TrailGitClones/magpie_git/magpie_py2_webins/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "wsgi.py", line 19, in <module>
    from inspire_magpie import application
  File "build/bdist.linux-x86_64/egg/inspire_magpie/__init__.py", line 20, in <module>
    from .api import get_cached_model
  File "build/bdist.linux-x86_64/egg/inspire_magpie/api.py", line 28, in <module>
    from magpie.evaluation.rank_metrics import mean_reciprocal_rank, r_precision, \
ImportError: No module named evaluation.rank_metrics
```

Please provide evaluation module for this.

**Comment by jstypka** [comment]
We removed evaluation modules from Magpie some time ago, Inspire-HEP has not been migrated - it's not really been maintained very well.

You can remove the evaluation code altogether or use [this gist](https://gist.github.com/bwhite/3726239) to compute some basic metrics for yourself
